# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Huectl < Formula
  desc "CLI for controlling Philips Hue lights via Hue API v2"
  homepage "https://github.com/mgrossma09/hue-cli"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgrossma09/hue-cli/releases/download/v0.0.6/huectl_0.0.6_darwin_amd64.tar.gz"
      sha256 "10b8dbf2e43c789d0adf9a889d85ce359eac43c0264e0fc1204e742c395640fe"

      def install
        bin.install "huectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgrossma09/hue-cli/releases/download/v0.0.6/huectl_0.0.6_darwin_arm64.tar.gz"
      sha256 "de8527c37e707408e3aeb5ea08e5efabcdc23fa46d839faa88ef401d48a242e5"

      def install
        bin.install "huectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgrossma09/hue-cli/releases/download/v0.0.6/huectl_0.0.6_linux_amd64.tar.gz"
      sha256 "27ca417960e147a4af74e24ade128ec860ca0a8ace1be92e6b128a0353b06fc9"
      def install
        bin.install "huectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgrossma09/hue-cli/releases/download/v0.0.6/huectl_0.0.6_linux_arm64.tar.gz"
      sha256 "32d48248f8bb31b08659f7428722efd9abbe43886f29fc65e42818a4b02d2e36"
      def install
        bin.install "huectl"
      end
    end
  end
end
